const icons={plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/>',x:'<path d="m6 6 12 12M18 6 6 18"/>',boxes:'<path d="m12 2 7 4v8l-7 4-7-4V6l7-4Z"/><path d="m5 6 7 4 7-4M12 10v8"/>',check:'<path d="m5 12 4 4L19 6"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',trash:'<path d="M3 6h18M8 6V4h8v2M19 6l-1 15H6L5 6"/><path d="M10 11v5M14 11v5"/>',more:'<circle cx="12" cy="5" r="1" fill="currentColor"/><circle cx="12" cy="12" r="1" fill="currentColor"/><circle cx="12" cy="19" r="1" fill="currentColor"/>',edit:'<path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L7 19l-4 1 1-4Z"/>'};
Object.assign(icons,{
 grid:'<rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/>',
 hexagon:'<path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z"/><circle cx="12" cy="12" r="3"/>',
 'share-2':'<circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><path d="m8.6 10.5 6.8-4M8.6 13.5l6.8 4"/>',
 users:'<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75"/>',
 bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M13.7 21a2 2 0 0 1-3.4 0"/>',
 flame:'<path d="M12 22c4 0 7-3 7-7 0-3-1.5-5.5-4-7 .2 2-1 3-2 3-1.5-2-1-5-1-7-4 2-7 6-7 11 0 4 3 7 7 7Z"/>',
 'refresh-cw':'<path d="M21 12a9 9 0 0 0-15-6.7L3 8M3 3v5h5M3 12a9 9 0 0 0 15 6.7l3-2.7M21 21v-5h-5"/>',
 shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/><path d="m9 12 2 2 4-4"/>',
 'log-in':'<path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4M10 17l5-5-5-5M15 12H3"/>',
 'git-branch':'<circle cx="6" cy="3" r="2"/><circle cx="18" cy="6" r="2"/><circle cx="6" cy="21" r="2"/><path d="M6 5v14M18 8a9 9 0 0 1-9 9H6"/>',
 database:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 11v6c0 1.7 3.6 3 8 3s8-1.3 8-3v-6"/>',
 'book-open':'<path d="M2 4h6a4 4 0 0 1 4 4v12a3 3 0 0 0-3-3H2ZM22 4h-6a4 4 0 0 0-4 4v12a3 3 0 0 1 3-3h7Z"/>',
 'log-out':'<path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4M16 17l5-5-5-5M21 12H9"/>'
});document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">'+(icons[e.dataset.icon]||'')+'</svg>');
const galaxy={
 'MARS PhyServer':'name device_gnezdo_id ci_category_lu_description ci_id server_managed_ip device_ip_list server_cpu_core server_ram device_vendor device_model device_serial_number device_res_pool_lu_description device_standard_lu_description server_type_lu_description ci_owner_group_ref_description ci_resp_group_ref_description ci_status_lu_description ci_perimeter_lu_description ci_env_type_lu_description device_rack_ref_description device_dc_ref_description',
 'MARS Storage)':'name device_serial_number ci_env_type',
 'MARS Integration (UABD)':'name sftciconfiguration sftcistatus sftcienvtype sftsoftname sftsoftversion sftsofthostname sftciresponsiblegroup sftisboxedproduct sftciowner sftcidomain sftsoftdistributiverelease sftsoftrole sftciconfiguration4 itsmname itsmsyscriticalitycategory hstname hstcistatus hsthostipaddress hsthostosname hsthostosversion hstcienvtype hstciresponsiblegroup dbmsname dbmsdbmsdbname dbmsdbuniqname dbmsciid dbmsdbmsmainis dbmsalias dbmsdbmsenvtype dbmsciresponsiblegroup appplatformtype security_zone fqdn itsmcistatus hsthostiscloud hsthostnetworksegment sftcicreatetime sftsoftinstalltype dbmsdbmsrole',
 'MARS Integration (USP)':'id name sftciconfiguration sftcistatus sftcienvtype sftsoftname sftsoftversion sftsofthostname sftciresponsiblegroup sftisboxedproduct sftciowner sftcidomain sftsoftdistributiverelease sftsoftrole sftciconfiguration4 itsmname itsmsyscriticalitycategory hstname hstcistatus hsthostipaddress hsthostosname hsthostosversion hstcienvtype hstciresponsiblegroup appplatformtype security_zone fqdn itsmcistatus hsthostiscloud hsthostnetworksegment sftcicreatetime sftsoftinstalltype dbmsdbmsrole',
 'MARS Integration (HOSTOS)':'name domain_name fqdn altname ip hostcienvtype hostgroup hoststatus osver vendor model sn osname hosthostnetworksegment owner smid host_cld_service_id host_app_func_grp host_datacenter itsmname itsmsyscriticalitycategory smitenv itsysrisid smitgroup cluster_name cluster_type hostisappliance hostisblackbox hostnotneedmars hostcienvironment',
 'MARS Integration (SANSW)':'name device_alt_serial ci_env_type',
 'ИТ-Система':'name okii apdid risid number status contour ctowner itstype mircode category systemid direction number_is rpotarget rtotarget etlversion ssfullname ssitleader drpcomments environment businessline certnextdate certrequired sscontactname respfordevdept supportmanager publicshortname replacingowners softwarepackage criticalitystatus supportstreamname configitemcategory criticalitycategory responsiblegroupname continuitycoordinator respfordevsubdivisionname deputycontinuitycoordinator',
 'КЕ - ИС':'name okii type apdId risId number ctOwner itsType category mirCodes systemId architect shortCode targetIts createDate archiveUsing sourceSystem configItemType respForDevDept alternativeName publicShortName replacingOwners criticalityStatus isLifecycleStatus configItemCategory outOfServiceMethod criticalityCategory respForDevStreamName previousTargetIsStatus respForDevStreamNumber respForDevSubdivisionName respForDevSubdivisionNumber respForDevStreamExternalNumber respForDevSubdivisionExternalNumber'};
const $=id=>document.getElementById(id), labels={objects:['Объекты','объект'],types:['Типы объектов','тип объекта'],relations:['Связи','связь']};let active='objects',db,editingAttributeId=null,deletingAttributeId=null,editingTypeId=null,editingMonitoringObjectId=null,duplicateMonitoringObject=null,expandedObjectTypeIds=new Set();
function dbOpen(){return new Promise((ok,no)=>{let r=indexedDB.open('mars-object-registry',5);r.onupgradeneeded=()=>{let d=r.result,tx=r.transaction;['attributes','types','monitoringObjects','relations'].forEach(name=>{if(d.objectStoreNames.contains(name))tx.objectStore(name).clear();else d.createObjectStore(name,{keyPath:'id',autoIncrement:true})})};r.onsuccess=()=>{db=r.result;ok()};r.onerror=()=>no(r.error)})}
function storeRequest(store,method,value){return new Promise((ok,no)=>{let request=db.transaction(store,method==='getAll'?'readonly':'readwrite').objectStore(store)[method](...(method==='getAll'?[]:[value]));request.onsuccess=()=>ok(request.result);request.onerror=()=>no(request.error)})}
async function getStoreItems(store){return (await storeRequest(store,'getAll')).reverse()}
const getAll=()=>getStoreItems('attributes'),save=x=>storeRequest('attributes','add',x),updateAttribute=x=>storeRequest('attributes','put',x),deleteAttribute=id=>storeRequest('attributes','delete',id),getTypes=()=>getStoreItems('types'),saveType=x=>storeRequest('types','add',x),updateType=x=>storeRequest('types','put',x),getMonitoringObjects=()=>getStoreItems('monitoringObjects'),saveMonitoringObject=x=>storeRequest('monitoringObjects',x.id?'put':'add',x),getRelations=()=>getStoreItems('relations'),saveRelation=x=>storeRequest('relations','add',x);
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function toast(s){$('toast').querySelector('span').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3000)}
async function updateCounts(){let [objects,types,relations]=await Promise.all([getMonitoringObjects(),getTypes(),getRelations()]);document.querySelector('[data-tab="objects"] .count').textContent=objects.length;document.querySelector('[data-tab="types"] .count').textContent=types.length;document.querySelector('[data-tab="relations"] .count').textContent=relations.length}
function icon(name){return '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round">'+icons[name]+'</svg>'}
/* UI-логика отключённой вкладки «Атрибуты» сохранена в комментарии.
async function render(){
  let all=await getAll(),query=$('searchInput').value.toLowerCase(),type=$('objectTypeFilter').dataset.value||'';
  let types=[...new Set((await getTypes()).map(x=>x.name).filter(Boolean))].sort();
  let currentType=$('objectTypeFilter').dataset.value||'';if(currentType&&!types.includes(currentType))currentType='';
  $('objectTypeFilter').dataset.value=currentType;$('objectTypeFilter').querySelector('.type-filter-value').textContent=currentType||'Все';
  $('objectTypeFilterMenu').innerHTML='<button type="button" data-value="">Все</button>'+types.map(x=>'<button type="button" data-value="'+esc(x)+'">'+esc(x)+'</button>').join('');
  $('objectTypeFilterMenu').querySelectorAll('button').forEach(button=>button.onclick=e=>{e.stopPropagation();$('objectTypeFilter').dataset.value=button.dataset.value;$('objectTypeFilter').querySelector('.type-filter-value').textContent=button.dataset.value||'Все';$('objectTypeFilterMenu').hidden=true;$('objectTypeFilter').setAttribute('aria-expanded','false');render()});type=currentType;
  let a=all.filter(x=>x.name.toLowerCase().includes(query)&&(!type||x.objectType===type));
  $('attributesRows').innerHTML=a.map(x=>'<div class="attribute-row"><strong>'+esc(x.name)+'</strong><span>'+esc(x.objectType||'—')+'</span><span>'+(x.collection?esc(x.collection)+' · <code>'+esc(x.galaxyAttribute)+'</code>':'—')+'</span><div class="row-actions"><button class="more-button" data-id="'+x.id+'" aria-label="Действия" aria-expanded="false">'+icon('more')+'</button><div class="actions-popup" hidden><button data-action="edit">'+icon('edit')+'<span>Изменить</span></button><button class="danger-action" data-action="delete">'+icon('trash')+'<span>Удалить</span></button></div></div></div>').join('');
  $('emptyState').hidden=!!a.length;$('attributesList').hidden=!a.length;document.querySelector('[data-tab="attributes"] .count').textContent=all.length;
  $('addButton').hidden=false;$('emptyAddButton').hidden=all.length>0;
  document.querySelectorAll('.more-button').forEach(button=>button.onclick=e=>{e.stopPropagation();let popup=button.nextElementSibling,opening=popup.hidden;document.querySelectorAll('.actions-popup').forEach(x=>x.hidden=true);document.querySelectorAll('.more-button').forEach(x=>x.setAttribute('aria-expanded','false'));popup.hidden=!opening;button.setAttribute('aria-expanded',String(opening))});
  document.querySelectorAll('#attributesRows [data-action="edit"]').forEach(button=>button.onclick=()=>openEditAttribute(+button.closest('.row-actions').querySelector('.more-button').dataset.id));
  document.querySelectorAll('#attributesRows [data-action="delete"]').forEach(button=>button.onclick=()=>openDeleteAttribute(+button.closest('.row-actions').querySelector('.more-button').dataset.id));
}
*/
async function renderTypes(){
  let all=await getTypes(),t=all.filter(x=>x.name.toLowerCase().includes($('searchInput').value.toLowerCase()));
  $('typesRows').innerHTML=t.map(x=>'<div class="type-row" data-id="'+x.id+'"><strong class="type-name">'+esc(x.name)+'</strong><span>'+esc(getTypeObjectFields(x).map(field=>field.label).join(', ')||'Атрибуты не выбраны')+'</span><span>'+esc(x.cmdbCollection||'—')+'</span><div class="row-actions"><button class="more-button" aria-label="Действия" aria-expanded="false">'+icon('more')+'</button><div class="actions-popup" hidden><button data-action="edit">'+icon('edit')+'<span>Изменить</span></button><button class="danger-action" data-action="delete">'+icon('trash')+'<span>Удалить</span></button></div></div></div>').join('');
  $('emptyState').hidden=!!t.length;$('typesList').hidden=!t.length;document.querySelector('[data-tab="types"] .count').textContent=all.length;
  document.querySelectorAll('#typesRows .more-button').forEach(button=>button.onclick=e=>{e.stopPropagation();let popup=button.nextElementSibling,opening=popup.hidden;document.querySelectorAll('.actions-popup').forEach(x=>x.hidden=true);popup.hidden=!opening;button.setAttribute('aria-expanded',String(opening))});
  document.querySelectorAll('#typesRows [data-action="edit"]').forEach(button=>button.onclick=e=>{e.stopPropagation();openEditType(+button.closest('.type-row').dataset.id)});
  document.querySelectorAll('#typesRows [data-action="delete"]').forEach(button=>button.onclick=async e=>{e.stopPropagation();let id=+button.closest('.type-row').dataset.id,type=all.find(x=>x.id===id);if(!confirm('Удалить тип «'+type.name+'»?'))return;let r=db.transaction('types','readwrite').objectStore('types').delete(id);r.onsuccess=async()=>{await renderTypes();await updateCounts();toast('Тип удалён')}})
}
async function renderObjects(){let [all,types]=await Promise.all([getMonitoringObjects(),getTypes()]),query=$('searchInput').value.toLowerCase(),objects=all.filter(object=>(object.name+' '+object.typeName).toLowerCase().includes(query)),typeMap=new Map(types.map(type=>[type.id,type])),groups=new Map();objects.forEach(object=>{let key=String(object.typeId||object.typeName||'unknown');if(!groups.has(key))groups.set(key,{key,type:typeMap.get(object.typeId),name:object.typeName||'Без типа',objects:[]});groups.get(key).objects.push(object)});$('objectsRows').innerHTML=[...groups.values()].map(group=>{let fields=getTypeObjectFields(group.type||{}),expanded=expandedObjectTypeIds.has(group.key),columns='minmax(190px,1.2fr)'+fields.map(()=>' minmax(150px,1fr)').join('');return '<section class="object-type-group '+(expanded?'expanded':'')+'" data-type-key="'+esc(group.key)+'"><button type="button" class="object-type-toggle" aria-expanded="'+expanded+'"><span class="object-type-chevron">›</span><strong>'+esc(group.name)+'</strong><span class="object-type-count">'+group.objects.length+'</span></button><div class="object-type-table" '+(expanded?'':'hidden')+'><div class="object-type-table-head" style="grid-template-columns:'+columns+'"><span>Название объекта</span>'+fields.map(field=>'<span>'+esc(field.label)+'</span>').join('')+'</div>'+group.objects.map(object=>'<div class="object-type-table-row" style="grid-template-columns:'+columns+'"><strong>'+esc(object.name)+'</strong>'+fields.map(field=>'<span>'+esc(object.values?.[field.key]||'—')+'</span>').join('')+'</div>').join('')+'</div></section>'}).join('');$('objectsRows').querySelectorAll('.object-type-toggle').forEach(button=>button.onclick=()=>{let group=button.closest('.object-type-group'),key=group.dataset.typeKey,expanded=!expandedObjectTypeIds.has(key);if(expanded)expandedObjectTypeIds.add(key);else expandedObjectTypeIds.delete(key);group.classList.toggle('expanded',expanded);button.setAttribute('aria-expanded',String(expanded));group.querySelector('.object-type-table').hidden=!expanded});$('emptyState').hidden=!!objects.length;$('objectsList').hidden=!objects.length;document.querySelector('[data-tab="objects"] .count').textContent=all.length;$('emptyAddButton').hidden=all.length>0}
async function renderRelations(){let all=await getRelations(),query=$('searchInput').value.toLowerCase(),relations=all.filter(x=>(x.typeFromName+' '+x.attributeFromName+' '+x.typeToName+' '+x.attributeToName).toLowerCase().includes(query));$('relationsRows').innerHTML=relations.map(x=>'<div class="relation-row"><strong>'+esc(x.typeFromName)+'</strong><span>'+esc(x.attributeFromName)+'</span><strong>'+esc(x.typeToName)+'</strong><span>'+esc(x.attributeToName)+'</span></div>').join('');$('emptyState').hidden=!!relations.length;$('relationsList').hidden=!relations.length;document.querySelector('[data-tab="relations"] .count').textContent=all.length}
function tab(id){active=id;let [p,s]=labels[id],typeFilter=$('objectTypeFilter'),typeFilterWrap=$('objectTypeFilterWrap');document.querySelector('.content-card').classList.remove('attributes-view');typeFilterWrap.classList.add('is-inactive');typeFilter.disabled=true;typeFilterWrap.setAttribute('aria-hidden','true');document.querySelectorAll('.tab').forEach(b=>{let selected=b.dataset.tab===id;b.classList.toggle('active',selected);b.setAttribute('aria-selected',String(selected))});$('emptyTitle').textContent=p+' ещё не добавлены';$('emptyText').textContent='Создайте '+(id==='relations'?'первую':'первый')+' '+s+', чтобы начать вести реестр.';[$('addButton'),$('emptyAddButton')].forEach(b=>{b.hidden=false;b.querySelector('span').textContent='Добавить '+s});$('objectsList').hidden=true;$('typesList').hidden=true;$('relationsList').hidden=true;$('emptyState').hidden=false;if(id==='objects')renderObjects();if(id==='types')renderTypes();if(id==='relations')renderRelations()}
function syncMappingFields(){
  const enabled=$('mappingToggle').getAttribute('aria-checked')==='true';
  $('mappingFields').hidden=!enabled;
  $('mappingToggle').setAttribute('aria-expanded',String(enabled));
}
function isValidCmdbCustomName(value){return /^[\x20-\x7E]*$/.test(value)}
function validateCmdbCustomNames(){let valid=true;$('cmdbAttributes').querySelectorAll('.cmdb-attribute-row').forEach(row=>{let checkbox=row.querySelector('input[type="checkbox"]'),input=row.querySelector('.cmdb-custom-name'),invalid=checkbox.checked&&!isValidCmdbCustomName(input.value);row.classList.toggle('invalid',invalid);if(invalid)valid=false});return valid}
function syncCmdbSelectAll(){let checkboxes=[...$('cmdbAttributes').querySelectorAll('input[type="checkbox"]')],checked=checkboxes.filter(input=>input.checked).length;$('cmdbSelectAll').checked=checkboxes.length>0&&checked===checkboxes.length;$('cmdbSelectAll').indeterminate=checked>0&&checked<checkboxes.length;$('cmdbSelectedCount').textContent='Выбрано: '+checked;$('cmdbSelectedCount').hidden=checked===0}
function renderCmdbAttributes(collection,selected=[]){let selectedMap=new Map(selected.map(item=>typeof item==='string'?[item,'']:[item.name,item.customName||''])),attributes=(galaxy[collection]||'').split(' ').filter(Boolean);$('cmdbAttributes').innerHTML=attributes.map(name=>{let checked=selectedMap.has(name),customName=selectedMap.get(name)||'';return '<div class="cmdb-attribute-row"><label><input type="checkbox" value="'+esc(name)+'" '+(checked?'checked':'')+'><span>'+esc(name)+'</span></label><div><input class="cmdb-custom-name" type="text" maxlength="120" value="'+esc(customName)+'" placeholder="Название атрибута в MARS" '+(checked?'':'disabled')+'><small class="cmdb-name-error">Только латиница, цифры и спецсимволы</small></div></div>'}).join('');$('cmdbAttributes').querySelectorAll('.cmdb-attribute-row').forEach(row=>{let checkbox=row.querySelector('input[type="checkbox"]'),customName=row.querySelector('.cmdb-custom-name');checkbox.onclick=e=>e.stopPropagation();checkbox.onchange=()=>{customName.disabled=!checkbox.checked;row.classList.remove('invalid');syncCmdbSelectAll()};customName.oninput=()=>row.classList.toggle('invalid',checkbox.checked&&!isValidCmdbCustomName(customName.value))});$('cmdbAttributesBlock').hidden=!collection;document.querySelector('.type-form-modal').classList.toggle('has-attributes',!!collection);$('cmdbAttributesContent').hidden=false;$('cmdbAttributesToggle').setAttribute('aria-expanded','true');syncCmdbSelectAll()}
function hideCmdbCollectionOptions(){$('cmdbCollectionOptions').hidden=true;$('cmdbCollectionInput').setAttribute('aria-expanded','false')}
function positionCmdbCollectionOptions(){let dropdown=document.querySelector('.cmdb-collection-dropdown'),inputRect=$('cmdbCollectionInput').getBoundingClientRect(),menu=$('cmdbCollectionOptions'),menuHeight=Math.min(menu.scrollHeight,280),spaceBelow=window.innerHeight-inputRect.bottom-12,spaceAbove=inputRect.top-12;dropdown.classList.toggle('open-up',spaceBelow<menuHeight&&spaceAbove>spaceBelow)}
async function renderCmdbCollectionOptions(query=''){let normalized=query.trim().toLowerCase(),selected=$('cmdbCollectionInput').value,types=await getTypes(),occupied=new Set(types.filter(type=>type.id!==editingTypeId&&type.cmdbCollection).map(type=>type.cmdbCollection)),collections=Object.keys(galaxy).filter(name=>name.toLowerCase().includes(normalized));$('cmdbCollectionOptions').innerHTML=collections.map(name=>'<button type="button" data-value="'+esc(name)+'" class="'+(name===selected?'is-selected':'')+'" '+(occupied.has(name)?'disabled title="Коллекция уже связана с другим типом объектов"':'')+'>'+esc(name)+'</button>').join('')||'<p>Коллекции не найдены</p>';$('cmdbCollectionOptions').querySelectorAll('button:not(:disabled)').forEach(button=>button.onclick=()=>selectCmdbCollection(button.dataset.value));$('cmdbCollectionOptions').hidden=false;positionCmdbCollectionOptions();$('cmdbCollectionInput').setAttribute('aria-expanded','true');if(!query){let selectedOption=$('cmdbCollectionOptions').querySelector('.is-selected:not(:disabled)');if(selectedOption)selectedOption.focus({preventScroll:true})}}
function selectCmdbCollection(collection,selectedAttributes=[]){$('cmdbCollectionInput').value=collection;hideCmdbCollectionOptions();renderCmdbAttributes(collection,selectedAttributes);$('cmdbCollectionError').classList.remove('visible')}
function renderCmdbCollections(selectedCollection='',selectedAttributes=[]){$('cmdbCollectionInput').value=selectedCollection;$('cmdbCollectionInput').onfocus=()=>renderCmdbCollectionOptions('');$('cmdbCollectionInput').onclick=e=>{e.stopPropagation();renderCmdbCollectionOptions('')};$('cmdbCollectionInput').oninput=()=>{let collection=$('cmdbCollectionInput').value;renderCmdbCollectionOptions(collection);if(Object.hasOwn(galaxy,collection))renderCmdbAttributes(collection);else{$('cmdbAttributesBlock').hidden=true;$('cmdbAttributes').innerHTML=''}};renderCmdbAttributes(selectedCollection,selectedAttributes)}
function resetCmdbMapping(collection='',attributes=[]){$('cmdbCollectionError').classList.remove('visible');document.querySelector('.cmdb-collection-dropdown').classList.remove('open-up');if(collection)renderCmdbCollections(collection,attributes);else{$('cmdbCollectionInput').value='';$('cmdbCollectionOptions').innerHTML='';hideCmdbCollectionOptions();$('cmdbAttributes').innerHTML='';$('cmdbAttributesBlock').hidden=true;document.querySelector('.type-form-modal').classList.remove('has-attributes')}}
let manualAttributeCounter=0;
function syncManualAttributeButton(){let inputs=[...$('manualAttributeRows').querySelectorAll('input')],blocked=inputs.some(input=>!input.value.trim()||!isValidCmdbCustomName(input.value));$('addTypeAttribute').disabled=blocked}
function addManualAttribute(attribute={}){let id=attribute.id||'manual-'+Date.now()+'-'+(++manualAttributeCounter),row=document.createElement('div');row.className='manual-attribute-row';row.dataset.id=id;row.innerHTML='<input type="text" maxlength="120" value="'+esc(attribute.name||'')+'" placeholder="Название атрибута в MARS"><small>Только латиница, цифры и спецсимволы</small>';$('manualAttributeRows').append(row);let input=row.querySelector('input');input.oninput=()=>{row.classList.toggle('invalid',!!input.value&&!isValidCmdbCustomName(input.value));syncManualAttributeButton()};syncManualAttributeButton();if(!attribute.name)input.focus()}
function renderManualAttributes(attributes=[]){$('manualAttributeRows').innerHTML='';attributes.forEach(addManualAttribute);syncManualAttributeButton()}
function validateManualAttributes(){let valid=true;$('manualAttributeRows').querySelectorAll('.manual-attribute-row').forEach(row=>{let input=row.querySelector('input'),invalid=!input.value.trim()||!isValidCmdbCustomName(input.value);row.classList.toggle('invalid',invalid);if(invalid)valid=false});return valid}
function getManualAttributes(){return [...$('manualAttributeRows').querySelectorAll('.manual-attribute-row')].map(row=>({id:row.dataset.id,name:row.querySelector('input').value.trim()}))}
function setAttributeMode(mode){document.querySelectorAll('[name="attributeMode"]').forEach(input=>input.checked=input.value===mode);$('manualAttributesSection').hidden=mode!=='manual';$('cmdbFields').hidden=mode!=='cmdb';if(mode==='cmdb'&&!$('cmdbCollectionInput').onfocus)renderCmdbCollections()}
async function populateObjectTypes(selected=''){
  let types=await getTypes();
  $('objectType').innerHTML='<option value="">Не выбран</option>'+types.map(x=>'<option value="'+esc(x.name)+'">'+esc(x.name)+'</option>').join('');
  $('objectType').value=selected;
}
async function openEditAttribute(id){
  let item=(await getAll()).find(x=>x.id===id);if(!item)return;
  editingAttributeId=id;$('modalTitle').textContent='Изменить атрибут';$('attributeName').value=item.name;await populateObjectTypes(item.objectType||'');
  let mapped=!!item.collection;$('mappingToggle').setAttribute('aria-checked',String(mapped));syncMappingFields();
  $('galaxyCollection').value=item.collection||'';$('galaxyCollection').dispatchEvent(new Event('change'));$('galaxyAttribute').value=item.galaxyAttribute||'';
  $('attributeModal').classList.add('open');$('attributeModal').setAttribute('aria-hidden','false');$('attributeName').focus();
}
async function openDeleteAttribute(id){let item=(await getAll()).find(x=>x.id===id);if(!item)return;deletingAttributeId=id;$('deleteAttributeText').textContent='Атрибут «'+item.name+'» будет удалён из реестра.';$('deleteAttributeModal').classList.add('open');$('deleteAttributeModal').setAttribute('aria-hidden','false')}
function closeDeleteAttribute(){$('deleteAttributeModal').classList.remove('open');$('deleteAttributeModal').setAttribute('aria-hidden','true');deletingAttributeId=null}
async function syncTypeAttributeAssignments(typeId,typeName,selectedIds,previousName=''){let selected=new Set(selectedIds),attributes=await getAll();await Promise.all(attributes.map(attribute=>{let nextType=selected.has(attribute.id)?typeName:((attribute.objectType===previousName||attribute.objectType===typeName)?'':attribute.objectType);if((attribute.objectType||'')===nextType)return Promise.resolve();return updateAttribute({...attribute,objectType:nextType})}));let types=await getTypes();await Promise.all(types.filter(type=>type.id!==typeId&&(type.attributes||[]).some(attribute=>selected.has(attribute.id))).map(type=>updateType({...type,attributes:(type.attributes||[]).filter(attribute=>!selected.has(attribute.id))})))}
async function repairAttributeTypeLinks(){let [types,attributes]=await Promise.all([getTypes(),getAll()]),typeByAttribute=new Map();types.forEach(type=>(type.attributes||[]).forEach(attribute=>{if(!typeByAttribute.has(attribute.id))typeByAttribute.set(attribute.id,type.name)}));await Promise.all(attributes.filter(attribute=>typeByAttribute.has(attribute.id)&&attribute.objectType!==typeByAttribute.get(attribute.id)).map(attribute=>updateAttribute({...attribute,objectType:typeByAttribute.get(attribute.id)})))}
async function syncAttributeTypeMembership(attribute){let types=await getTypes();await Promise.all(types.map(type=>{let without=(type.attributes||[]).filter(item=>item.id!==attribute.id),shouldContain=type.name===attribute.objectType,next=shouldContain?[...without,attribute]:without;if(next.length===(type.attributes||[]).length&&next.every((item,index)=>item.id===(type.attributes||[])[index]?.id&&item.name===(type.attributes||[])[index]?.name))return Promise.resolve();return updateType({...type,attributes:next})}))}
async function syncCmdbAttributesToRegistry(type){let all=await getAll(),existing=all.filter(attribute=>attribute.source==='cmdb-type'&&attribute.sourceTypeId===type.id),selected=type.cmdbAttributes||[],selectedNames=new Set(selected.map(attribute=>typeof attribute==='string'?attribute:attribute.name));await Promise.all(selected.map(async attribute=>{let cmdbName=typeof attribute==='string'?attribute:attribute.name,customName=typeof attribute==='string'?'':attribute.customName||'',current=existing.find(item=>item.galaxyAttribute===cmdbName),item={...(current||{}),name:customName||cmdbName,objectType:type.name,collection:type.cmdbCollection,galaxyAttribute:cmdbName,source:'cmdb-type',sourceTypeId:type.id};if(current)await updateAttribute(item);else await save(item)}));await Promise.all(existing.filter(attribute=>!selectedNames.has(attribute.galaxyAttribute)).map(attribute=>deleteAttribute(attribute.id)))}
async function syncManualAttributesToRegistry(type){let all=await getAll(),existing=all.filter(attribute=>attribute.source==='manual-type'&&attribute.sourceTypeId===type.id),selected=type.manualAttributes||[],selectedIds=new Set(selected.map(attribute=>attribute.id));await Promise.all(selected.map(async attribute=>{let current=existing.find(item=>item.sourceAttributeId===attribute.id),item={...(current||{}),name:attribute.name,objectType:type.name,collection:'',galaxyAttribute:'',source:'manual-type',sourceTypeId:type.id,sourceAttributeId:attribute.id};if(current)await updateAttribute(item);else await save(item)}));await Promise.all(existing.filter(attribute=>!selectedIds.has(attribute.sourceAttributeId)).map(attribute=>deleteAttribute(attribute.id)))}
async function syncTypeAttributesToRegistry(type){await syncManualAttributesToRegistry(type);await syncCmdbAttributesToRegistry(type)}
async function syncAllTypeAttributesToRegistry(){for(let type of await getTypes())await syncTypeAttributesToRegistry(type)}
function getTypeObjectFields(type){let local=(type.attributes||[]).map(attribute=>({key:String(attribute.id),label:attribute.nameRu||attribute.name})),manual=(type.manualAttributes||[]).map(attribute=>({key:attribute.id,label:attribute.name})),cmdb=(type.cmdbAttributes||[]).map(attribute=>typeof attribute==='string'?{key:'cmdb:'+attribute,label:attribute}:{key:'cmdb:'+attribute.name,label:attribute.customName||attribute.name});return [...local,...manual,...cmdb]}
async function openEditType(id){let type=(await getTypes()).find(x=>x.id===id);if(!type)return;editingTypeId=id;$('typeModalTitle').textContent='Изменить тип объекта';$('typeName').value=type.name;renderManualAttributes(type.manualAttributes||[]);resetCmdbMapping(type.cmdbCollection||'',type.cmdbAttributes||[]);setAttributeMode(type.cmdbCollection?'cmdb':'manual');$('typeModal').classList.add('open');$('typeModal').setAttribute('aria-hidden','false')}
async function openTypeDetails(id){let type=(await getTypes()).find(x=>x.id===id);if(!type)return;let fields=getTypeObjectFields(type),objects=await getMonitoringObjects(),rows=objects.filter(x=>x.typeId===id),columns='minmax(190px,1.2fr) '+fields.map(()=>'minmax(150px,1fr)').join(' ');$('typeDetailsTitle').textContent=type.name;$('typeDetailsHead').style.gridTemplateColumns=columns;$('typeDetailsHead').innerHTML='<span>Объект мониторинга</span>'+fields.map(field=>'<span>'+esc(field.label)+'</span>').join('');$('typeDetailsRows').innerHTML=rows.length?rows.map(object=>'<div class="details-row" style="grid-template-columns:'+columns+'"><strong>'+esc(object.name)+'</strong>'+fields.map(field=>'<span>'+esc(object.values?.[field.key]||'—')+'</span>').join('')+'</div>').join(''):'<div class="details-empty">Объекты мониторинга этого типа ещё не добавлены.</div>';$('typeDetailsModal').classList.add('open');$('typeDetailsModal').setAttribute('aria-hidden','false')}
function closeTypeDetails(){$('typeDetailsModal').classList.remove('open');$('typeDetailsModal').setAttribute('aria-hidden','true')}
async function openMonitoringObject(){let types=await getTypes();editingMonitoringObjectId=null;duplicateMonitoringObject=null;$('monitoringObjectForm').reset();$('monitoringObjectType').innerHTML='<option value="">Выберите тип</option>'+types.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('');$('monitoringObjectIdentity').hidden=false;$('monitoringObjectCard').hidden=true;$('duplicateNotice').hidden=true;$('continueMonitoringObject').textContent='Продолжить';$('monitoringObjectModal').classList.add('open');$('monitoringObjectModal').setAttribute('aria-hidden','false');$('monitoringObjectName').focus()}
function closeMonitoringObject(){$('monitoringObjectModal').classList.remove('open');$('monitoringObjectModal').setAttribute('aria-hidden','true');editingMonitoringObjectId=null;duplicateMonitoringObject=null}
async function showMonitoringCard(object=null){let typeId=+$('monitoringObjectType').value,type=(await getTypes()).find(x=>x.id===typeId);if(!type)return;let fields=getTypeObjectFields(type);editingMonitoringObjectId=object?.id||null;$('monitoringObjectIdentity').hidden=true;$('duplicateNotice').hidden=true;$('monitoringObjectCard').hidden=false;$('monitoringObjectCardTitle').textContent=$('monitoringObjectName').value.trim()+' · '+type.name;$('monitoringAttributeFields').innerHTML=fields.map(field=>'<label class="form-label">'+esc(field.label)+'<input data-attribute-id="'+esc(field.key)+'" value="'+esc(object?.values?.[field.key]||'')+'" placeholder="Введите значение" /></label>').join('')||'<p class="details-empty">У этого типа нет атрибутов.</p>';$('continueMonitoringObject').textContent='Сохранить'}
async function openRelationModal(){let types=await getTypes();$('relationForm').reset();$('relationTypeFrom').innerHTML='<option value="">Выберите тип</option>'+types.map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('');$('relationAttributeFrom').innerHTML='<option value="">Сначала выберите тип</option>';$('relationTypeTo').innerHTML='<option value="">Сначала выберите первый тип</option>';$('relationAttributeTo').innerHTML='<option value="">Сначала выберите тип</option>';[$('relationAttributeFrom'),$('relationTypeTo'),$('relationAttributeTo')].forEach(x=>x.disabled=true);$('relationModal').classList.add('open');$('relationModal').setAttribute('aria-hidden','false')}
function closeRelationModal(){$('relationModal').classList.remove('open');$('relationModal').setAttribute('aria-hidden','true');$('relationForm').reset();$('relationForm').querySelectorAll('.error').forEach(x=>x.classList.remove('visible'))}
async function openModal(){
  /* Ветка открытия формы вкладки «Атрибуты» отключена. */
  if(active==='types'){
    editingTypeId=null;$('typeModalTitle').textContent='Добавить тип объекта';renderManualAttributes();resetCmdbMapping();setAttributeMode('manual');
    $('typeModal').classList.add('open');$('typeModal').setAttribute('aria-hidden','false');$('typeName').focus();return
  }
  if(active==='relations'){await openRelationModal();return}
}
function closeModal(){$('attributeModal').classList.remove('open');$('attributeModal').setAttribute('aria-hidden','true');$('attributeForm').reset();editingAttributeId=null;$('modalTitle').textContent='Добавить атрибут';$('mappingToggle').setAttribute('aria-checked','false');syncMappingFields();document.querySelectorAll('.error').forEach(x=>x.classList.remove('visible'))}
function closeTypeModal(){$('typeModal').classList.remove('open');$('typeModal').setAttribute('aria-hidden','true');$('typeForm').reset();editingTypeId=null;$('typeModalTitle').textContent='Добавить тип объекта';$('typeNameError').classList.remove('visible');renderManualAttributes();resetCmdbMapping();setAttributeMode('manual')}
Object.keys(galaxy).forEach(x=>$('galaxyCollection').add(new Option(x,x)));$('galaxyCollection').onchange=e=>{$('galaxyAttribute').innerHTML='<option value="">Выберите атрибут</option>';(galaxy[e.target.value]||'').split(' ').filter(Boolean).forEach(x=>$('galaxyAttribute').add(new Option(x,x)));$('galaxyAttribute').disabled=!e.target.value};$('mappingToggle').onclick=()=>{$('mappingToggle').setAttribute('aria-checked',String($('mappingToggle').getAttribute('aria-checked')!=='true'));syncMappingFields()};syncMappingFields();
$('attributeModeOptions').onclick=e=>{let option=e.target.closest('[data-mode]');if(!option)return;e.preventDefault();setAttributeMode(option.dataset.mode)};
document.querySelectorAll('[name="attributeMode"]').forEach(input=>input.onchange=()=>{if(input.checked)setAttributeMode(input.value)});
$('cmdbSelectAll').onchange=()=>{$('cmdbAttributes').querySelectorAll('.cmdb-attribute-row').forEach(row=>{let checkbox=row.querySelector('input[type="checkbox"]'),customName=row.querySelector('.cmdb-custom-name');checkbox.checked=$('cmdbSelectAll').checked;customName.disabled=!checkbox.checked;row.classList.remove('invalid')});syncCmdbSelectAll()};$('cmdbSelectAll').onclick=e=>e.stopPropagation();$('cmdbAttributesToggle').onclick=()=>{let expanded=$('cmdbAttributesToggle').getAttribute('aria-expanded')==='true';$('cmdbAttributesToggle').setAttribute('aria-expanded',String(!expanded));$('cmdbAttributesContent').hidden=expanded};
document.querySelector('.cmdb-collection-dropdown').onclick=e=>e.stopPropagation();
$('addButton').onclick=openModal;$('closeModal').onclick=closeModal;$('cancelModal').onclick=closeModal;$('attributeModal').onclick=e=>e.target===$('attributeModal')&&closeModal();$('searchInput').oninput=()=>{document.querySelector('.search-field').classList.toggle('has-value',!!$('searchInput').value);if(active==='objects')renderObjects();if(active==='types')renderTypes();if(active==='relations')renderRelations()};$('clearSearch').onclick=()=>{$('searchInput').value='';$('searchInput').dispatchEvent(new Event('input'))};$('menuToggle').onclick=()=>$('sidebar').classList.toggle('open');
$('objectTypeFilter').onclick=e=>{e.stopPropagation();let opening=$('objectTypeFilterMenu').hidden;$('objectTypeFilterMenu').hidden=!opening;$('objectTypeFilter').setAttribute('aria-expanded',String(opening))};document.addEventListener('click',()=>{hideCmdbCollectionOptions();$('objectTypeFilterMenu').hidden=true;$('objectTypeFilter').setAttribute('aria-expanded','false');document.querySelectorAll('.actions-popup').forEach(x=>x.hidden=true);document.querySelectorAll('.more-button').forEach(x=>x.setAttribute('aria-expanded','false'))});
$('closeTypeModal').onclick=closeTypeModal;$('cancelTypeModal').onclick=()=>{closeTypeModal();tab('types')};$('typeModal').onclick=e=>e.target===$('typeModal')&&closeTypeModal();
$('closeDeleteAttributeModal').onclick=closeDeleteAttribute;$('cancelDeleteAttribute').onclick=closeDeleteAttribute;$('deleteAttributeModal').onclick=e=>e.target===$('deleteAttributeModal')&&closeDeleteAttribute();$('confirmDeleteAttribute').onclick=async()=>{if(deletingAttributeId===null)return;let id=deletingAttributeId;try{await deleteAttribute(id);closeDeleteAttribute();await render();toast('Атрибут удалён')}catch(err){console.error(err);toast('Не удалось удалить атрибут')}};
$('addTypeAttribute').onclick=()=>addManualAttribute();
$('attributeForm').onsubmit=async e=>{e.preventDefault();let n=$('attributeName').value.trim(),m=$('mappingToggle').getAttribute('aria-checked')==='true',c=$('galaxyCollection').value,a=$('galaxyAttribute').value;[['nameError',!n],['collectionError',m&&!c],['galaxyAttributeError',m&&!a]].forEach(x=>$(x[0]).classList.toggle('visible',x[1]));if(!n||(m&&(!c||!a)))return;try{let isEdit=editingAttributeId!==null,previous=isEdit?(await getAll()).find(attribute=>attribute.id===editingAttributeId):null,item={...(previous||{}),name:n,objectType:$('objectType').value,collection:m?c:'',galaxyAttribute:m?a:''};if(isEdit){item.id=editingAttributeId;await updateAttribute(item)}else item.id=await save(item);await syncAttributeTypeMembership(item);closeModal();await render();await updateCounts();toast(isEdit?'Атрибут изменён':'Атрибут сохранён в локальной базе')}catch(err){console.error(err);toast('Не удалось сохранить атрибут')}};
$('typeForm').onsubmit=async e=>{e.preventDefault();let n=$('typeName').value.trim(),mode=document.querySelector('[name="attributeMode"]:checked').value,manualMode=mode==='manual',manualValid=!manualMode||validateManualAttributes(),manualAttributes=manualMode?getManualAttributes():[],cmdbCollection=$('cmdbCollectionInput').value,cmdbCollectionValid=Object.hasOwn(galaxy,cmdbCollection),cmdbCollectionAvailable=manualMode||!(await getTypes()).some(type=>type.id!==editingTypeId&&type.cmdbCollection===cmdbCollection),cmdbNamesValid=manualMode||validateCmdbCustomNames(),cmdbAttributes=[...$('cmdbAttributes').querySelectorAll('.cmdb-attribute-row')].filter(row=>row.querySelector('input[type="checkbox"]').checked).map(row=>({name:row.querySelector('input[type="checkbox"]').value,customName:row.querySelector('.cmdb-custom-name').value.trim()}));$('typeNameError').classList.toggle('visible',!n);$('cmdbCollectionError').textContent=!cmdbCollectionAvailable?'Эта коллекция уже связана с другим типом объектов':'Выберите коллекцию в CMDB';$('cmdbCollectionError').classList.toggle('visible',!manualMode&&(!cmdbCollectionValid||!cmdbCollectionAvailable));if(!n||!manualValid||(!manualMode&&(!cmdbCollectionValid||!cmdbCollectionAvailable||!cmdbNamesValid)))return;try{let isEdit=editingTypeId!==null,previousType=isEdit?(await getTypes()).find(x=>x.id===editingTypeId):null,item={name:n,attributes:previousType?.attributes||[],manualAttributes,cmdbCollection:manualMode?'':cmdbCollection,cmdbAttributes:manualMode?[]:cmdbAttributes};if(isEdit){item.id=editingTypeId;await updateType(item)}else item.id=await saveType(item);await syncTypeAttributesToRegistry(item);closeTypeModal();await renderTypes();await updateCounts();toast(isEdit?'Тип изменён':'Тип объекта сохранён')}catch(err){console.error(err);toast('Не удалось сохранить тип объекта')}};
$('saveAttributeButton').onclick=()=>{$('attributeForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))};
$('saveTypeButton').onclick=()=>{$('typeForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))};
function syncTabActionButtons(id){let isTypes=id==='types',isObjects=id==='objects';$('addTypeButton').classList.toggle('is-inactive',!isTypes);$('addMonitoringObject').classList.toggle('is-inactive',!isObjects);$('addButton').hidden=isTypes||isObjects}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{$('searchInput').value='';document.querySelector('.search-field').classList.remove('has-value');tab(b.dataset.tab);syncTabActionButtons(b.dataset.tab)});
$('addTypeButton').onclick=openModal;$('addMonitoringObject').onclick=openMonitoringObject;$('emptyAddButton').onclick=()=>active==='objects'?openMonitoringObject():openModal();$('closeMonitoringObject').onclick=closeMonitoringObject;$('cancelMonitoringObject').onclick=closeMonitoringObject;$('monitoringObjectModal').onclick=e=>e.target===$('monitoringObjectModal')&&closeMonitoringObject();
$('closeTypeDetails').onclick=closeTypeDetails;$('typeDetailsModal').onclick=e=>e.target===$('typeDetailsModal')&&closeTypeDetails();
$('editExistingObject').onclick=()=>duplicateMonitoringObject&&showMonitoringCard(duplicateMonitoringObject);
$('monitoringObjectForm').onsubmit=async e=>{e.preventDefault();let name=$('monitoringObjectName').value.trim(),typeId=+$('monitoringObjectType').value;$('monitoringObjectNameError').classList.toggle('visible',!name);$('monitoringObjectTypeError').classList.toggle('visible',!typeId);if(!name||!typeId)return;if($('monitoringObjectCard').hidden){let objects=await getMonitoringObjects(),duplicate=objects.find(x=>x.typeId===typeId&&x.name.toLowerCase()===name.toLowerCase());if(duplicate){duplicateMonitoringObject=duplicate;$('duplicateNotice').hidden=false;return}await showMonitoringCard();return}let type=(await getTypes()).find(x=>x.id===typeId),values={};$('monitoringAttributeFields').querySelectorAll('[data-attribute-id]').forEach(input=>values[input.dataset.attributeId]=input.value.trim());let item={name,typeId,typeName:type.name,values},isEdit=editingMonitoringObjectId!==null;if(isEdit)item.id=editingMonitoringObjectId;try{await saveMonitoringObject(item);closeMonitoringObject();await renderObjects();await updateCounts();toast(isEdit?'Объект изменён':'Объект мониторинга добавлен')}catch(err){console.error(err);toast('Не удалось сохранить объект')}};
$('continueMonitoringObject').onclick=async e=>{e.preventDefault();try{await $('monitoringObjectForm').onsubmit(new Event('submit',{cancelable:true}))}catch(err){console.error(err);toast('Не удалось открыть карточку объекта')}};
$('relationForm').querySelector('.save-button').textContent='Сохранить';$('closeRelationModal').onclick=closeRelationModal;$('cancelRelationModal').onclick=()=>{closeRelationModal();tab('relations');syncTabActionButtons('relations')};$('relationModal').onclick=e=>e.target===$('relationModal')&&closeRelationModal();
$('relationTypeFrom').onchange=async e=>{let types=await getTypes(),type=types.find(x=>x.id===+e.target.value);$('relationAttributeFrom').innerHTML='<option value="">Выберите атрибут</option>'+((type?.attributes||[]).map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join(''));$('relationAttributeFrom').disabled=!type;$('relationTypeTo').innerHTML='<option value="">Выберите тип</option>'+types.filter(x=>x.id!==type?.id).map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join('');$('relationTypeTo').disabled=!type;$('relationAttributeTo').innerHTML='<option value="">Сначала выберите тип</option>';$('relationAttributeTo').disabled=true};
$('relationTypeTo').onchange=async e=>{let type=(await getTypes()).find(x=>x.id===+e.target.value);$('relationAttributeTo').innerHTML='<option value="">Выберите атрибут</option>'+((type?.attributes||[]).map(x=>'<option value="'+x.id+'">'+esc(x.name)+'</option>').join(''));$('relationAttributeTo').disabled=!type};
$('relationForm').onsubmit=async e=>{e.preventDefault();let typeFrom=+$('relationTypeFrom').value,attributeFrom=+$('relationAttributeFrom').value,typeTo=+$('relationTypeTo').value,attributeTo=+$('relationAttributeTo').value;[['relationTypeFromError',!typeFrom],['relationAttributeFromError',!attributeFrom],['relationTypeToError',!typeTo],['relationAttributeToError',!attributeTo]].forEach(x=>$(x[0]).classList.toggle('visible',x[1]));if(!typeFrom||!attributeFrom||!typeTo||!attributeTo)return;let types=await getTypes(),from=types.find(x=>x.id===typeFrom),to=types.find(x=>x.id===typeTo),fromAttribute=(from.attributes||[]).find(x=>x.id===attributeFrom),toAttribute=(to.attributes||[]).find(x=>x.id===attributeTo);try{await saveRelation({typeFrom,typeFromName:from.name,attributeFrom,attributeFromName:fromAttribute.name,typeTo,typeToName:to.name,attributeTo,attributeToName:toAttribute.name});closeRelationModal();await renderRelations();await updateCounts();toast('Связь сохранена')}catch(err){console.error(err);toast('Не удалось сохранить связь')}};
$('relationForm').querySelector('.save-button').onclick=async e=>{e.preventDefault();await $('relationForm').onsubmit(new Event('submit',{cancelable:true}))};
dbOpen().then(async()=>{await repairAttributeTypeLinks();await syncAllTypeAttributesToRegistry();await updateCounts();tab('objects');syncTabActionButtons('objects')}).catch(err=>{console.error(err);toast('Не удалось открыть локальную базу')});
